### ISSUE TITLE
NLog assembly issue

### ISSUE THREAD

**Issue by RobThree** [logentries/le_nlog#11]
I had added the le_nlog NuGet package as [per the documentation](https://logentries.com/doc/dotnet/) but no logentries ever appeared. I was finally able to debug this using the following config change to create a logfile:

    <nlog internalLogFile="./test.log" internalLogLevel="Debug">

This logfile contained the following information:

    2013-06-11 17:35:31.2209 Info Loading assembly name: le_nlog
    2013-06-11 17:35:31.2209 Debug ScanAssembly('le_nlog, Version=2.1.7.0, Culture=neutral, PublicKeyToken=null','NLog.Targets.TargetAttribute','NLog.Targets.Target')
    2013-06-11 17:35:31.2729 Warn Type load exception: System.IO.FileLoadException: Could not load file or assembly 'NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    File name: 'NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'

    === Pre-bind state information ===
    LOG: User = MYPCNAME\MyUserName
    LOG: DisplayName = NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c
     (Fully-specified)
    LOG: Appbase = file:///C:/Users/MyUserName/Desktop/ConsoleApplication3/ConsoleApplication3/bin/Debug/
    LOG: Initial PrivatePath = NULL
    Calling assembly : le_nlog, Version=2.1.7.0, Culture=neutral, PublicKeyToken=null.
    ===
    LOG: This bind starts in default load context.
    LOG: Using application configuration file: C:\Users\MyUserName\Desktop\ConsoleApplication3\ConsoleApplication3\bin\Debug\ConsoleApplication3.vshost.exe.config
    LOG: Using host configuration file: 
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
    LOG: Post-policy reference: NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c
    LOG: Attempting download of new URL file:///C:/Users/MyUserName/Desktop/ConsoleApplication3/ConsoleApplication3/bin/Debug/NLog.DLL.
    WRN: Comparing the assembly name resulted in the mismatch: Build Number
    ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

    2013-06-11 17:35:31.2729 Debug ScanAssembly('le_nlog, Version=2.1.7.0, Culture=neutral, PublicKeyToken=null','NLog.Filters.FilterAttribute','NLog.Filters.Filter')
    2013-06-11 17:35:31.2899 Warn Type load exception: System.IO.FileLoadException: Could not load file or assembly 'NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    File name: 'NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'

    === Pre-bind state information ===
    LOG: User = MYPCNAME\MyUserName
    LOG: DisplayName = NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c
     (Fully-specified)
    LOG: Appbase = file:///C:/Users/MyUserName/Desktop/ConsoleApplication3/ConsoleApplication3/bin/Debug/
    LOG: Initial PrivatePath = NULL
    Calling assembly : le_nlog, Version=2.1.7.0, Culture=neutral, PublicKeyToken=null.
    ===
    LOG: This bind starts in default load context.
    LOG: Using application configuration file: C:\Users\MyUserName\Desktop\ConsoleApplication3\ConsoleApplication3\bin\Debug\ConsoleApplication3.vshost.exe.config
    LOG: Using host configuration file: 
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
    LOG: Post-policy reference: NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c
    LOG: Attempting download of new URL file:///C:/Users/MyUserName/Desktop/ConsoleApplication3/ConsoleApplication3/bin/Debug/NLog.DLL.
    WRN: Comparing the assembly name resulted in the mismatch: Build Number
    ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

    2013-06-11 17:35:31.2899 Debug ScanAssembly('le_nlog, Version=2.1.7.0, Culture=neutral, PublicKeyToken=null','NLog.LayoutRenderers.LayoutRendererAttribute','NLog.LayoutRenderers.LayoutRenderer')
    2013-06-11 17:35:31.3099 Warn Type load exception: System.IO.FileLoadException: Could not load file or assembly 'NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    File name: 'NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'

    === Pre-bind state information ===
    LOG: User = MYPCNAME\MyUserName
    LOG: DisplayName = NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c
     (Fully-specified)
    LOG: Appbase = file:///C:/Users/MyUserName/Desktop/ConsoleApplication3/ConsoleApplication3/bin/Debug/
    LOG: Initial PrivatePath = NULL
    Calling assembly : le_nlog, Version=2.1.7.0, Culture=neutral, PublicKeyToken=null.
    ===
    LOG: This bind starts in default load context.
    LOG: Using application configuration file: C:\Users\MyUserName\Desktop\ConsoleApplication3\ConsoleApplication3\bin\Debug\ConsoleApplication3.vshost.exe.config
    LOG: Using host configuration file: 
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
    LOG: Post-policy reference: NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c
    LOG: Attempting download of new URL file:///C:/Users/MyUserName/Desktop/ConsoleApplication3/ConsoleApplication3/bin/Debug/NLog.DLL.
    WRN: Comparing the assembly name resulted in the mismatch: Build Number
    ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

    2013-06-11 17:35:31.3129 Debug ScanAssembly('le_nlog, Version=2.1.7.0, Culture=neutral, PublicKeyToken=null','NLog.Layouts.LayoutAttribute','NLog.Layouts.Layout')
    2013-06-11 17:35:31.3299 Warn Type load exception: System.IO.FileLoadException: Could not load file or assembly 'NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    File name: 'NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'

    === Pre-bind state information ===
    LOG: User = MYPCNAME\MyUserName
    LOG: DisplayName = NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c
     (Fully-specified)
    LOG: Appbase = file:///C:/Users/MyUserName/Desktop/ConsoleApplication3/ConsoleApplication3/bin/Debug/
    LOG: Initial PrivatePath = NULL
    Calling assembly : le_nlog, Version=2.1.7.0, Culture=neutral, PublicKeyToken=null.
    ===
    LOG: This bind starts in default load context.
    LOG: Using application configuration file: C:\Users\MyUserName\Desktop\ConsoleApplication3\ConsoleApplication3\bin\Debug\ConsoleApplication3.vshost.exe.config
    LOG: Using host configuration file: 
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
    LOG: Post-policy reference: NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c
    LOG: Attempting download of new URL file:///C:/Users/MyUserName/Desktop/ConsoleApplication3/ConsoleApplication3/bin/Debug/NLog.DLL.
    WRN: Comparing the assembly name resulted in the mismatch: Build Number
    ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

    2013-06-11 17:35:31.3299 Debug ScanAssembly('le_nlog, Version=2.1.7.0, Culture=neutral, PublicKeyToken=null','NLog.Conditions.ConditionMethodsAttribute','NLog.Conditions.ConditionMethodAttribute')
    2013-06-11 17:35:31.3489 Warn Type load exception: System.IO.FileLoadException: Could not load file or assembly 'NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    File name: 'NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'

    === Pre-bind state information ===
    LOG: User = MYPCNAME\MyUserName
    LOG: DisplayName = NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c
     (Fully-specified)
    LOG: Appbase = file:///C:/Users/MyUserName/Desktop/ConsoleApplication3/ConsoleApplication3/bin/Debug/
    LOG: Initial PrivatePath = NULL
    Calling assembly : le_nlog, Version=2.1.7.0, Culture=neutral, PublicKeyToken=null.
    ===
    LOG: This bind starts in default load context.
    LOG: Using application configuration file: C:\Users\MyUserName\Desktop\ConsoleApplication3\ConsoleApplication3\bin\Debug\ConsoleApplication3.vshost.exe.config
    LOG: Using host configuration file: 
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
    LOG: Post-policy reference: NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c
    LOG: Attempting download of new URL file:///C:/Users/MyUserName/Desktop/ConsoleApplication3/ConsoleApplication3/bin/Debug/NLog.DLL.
    WRN: Comparing the assembly name resulted in the mismatch: Build Number
    ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

    2013-06-11 17:35:31.3489 Debug ScanAssembly('le_nlog, Version=2.1.7.0, Culture=neutral, PublicKeyToken=null','NLog.LayoutRenderers.AmbientPropertyAttribute','NLog.LayoutRenderers.LayoutRenderer')
    2013-06-11 17:35:31.3689 Warn Type load exception: System.IO.FileLoadException: Could not load file or assembly 'NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    File name: 'NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'

    === Pre-bind state information ===
    LOG: User = MYPCNAME\MyUserName
    LOG: DisplayName = NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c
     (Fully-specified)
    LOG: Appbase = file:///C:/Users/MyUserName/Desktop/ConsoleApplication3/ConsoleApplication3/bin/Debug/
    LOG: Initial PrivatePath = NULL
    Calling assembly : le_nlog, Version=2.1.7.0, Culture=neutral, PublicKeyToken=null.
    ===
    LOG: This bind starts in default load context.
    LOG: Using application configuration file: C:\Users\MyUserName\Desktop\ConsoleApplication3\ConsoleApplication3\bin\Debug\ConsoleApplication3.vshost.exe.config
    LOG: Using host configuration file: 
    LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
    LOG: Post-policy reference: NLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c
    LOG: Attempting download of new URL file:///C:/Users/MyUserName/Desktop/ConsoleApplication3/ConsoleApplication3/bin/Debug/NLog.DLL.
    WRN: Comparing the assembly name resulted in the mismatch: Build Number
    ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

    2013-06-11 17:35:31.3930 Error Error in Parsing Configuration File. Exception : NLog.NLogConfigurationException: Exception occurred when loading configuration from C:\Users\MyUserName\Desktop\ConsoleApplication3\ConsoleApplication3\bin\Debug\ConsoleApplication3.vshost.exe.config ---> System.ArgumentException: Target cannot be found: 'LogEntries'
       at NLog.Config.Factory`2.CreateInstance(String name)
       at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
       at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String baseDirectory)
       at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String baseDirectory)
       at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
       --- End of inner exception stack trace ---
    2013-06-11 17:35:31.3930 Debug --- NLog configuration dump. ---
    2013-06-11 17:35:31.3930 Debug Targets:
    2013-06-11 17:35:31.3930 Debug Rules:
    2013-06-11 17:35:31.3930 Debug --- End of NLog configuration dump ---
    2013-06-11 17:35:31.4100 Info Found 0 configuration items
    2013-06-11 17:35:31.4100 Debug Targets for ConsoleApplication1.Program by level:
    2013-06-11 17:35:31.4100 Debug Trace =>
    2013-06-11 17:35:31.4220 Debug Debug =>
    2013-06-11 17:35:31.4220 Debug Info =>
    2013-06-11 17:35:31.4220 Debug Warn =>
    2013-06-11 17:35:31.4220 Debug Error =>
    2013-06-11 17:35:31.4220 Debug Fatal =>

After some research I figured out a [binding-redirect](http://msdn.microsoft.com/en-us/library/2fc472t2.aspx) might work; and so it did. I had to add the following to my app.config:

    <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
          <dependentAssembly>
            <assemblyIdentity name="NLog"
                              publicKeyToken="5120e14c03d0593c"
                              culture="neutral" />
            <bindingRedirect oldVersion="2.0.0.0"
                             newVersion="2.0.1.0"/>
          </dependentAssembly>
        </assemblyBinding>
    </runtime>

Which results in a app.config that looks like:

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <configSections>
        <section name="nlog" type="NLog.Config.ConfigSectionHandler, NLog"/>
      </configSections>
      <appSettings>
        <add key="LOGENTRIES_TOKEN" value="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" />
      </appSettings>
      <nlog internalLogFile="./test.log" internalLogLevel="Debug">
        <extensions>
          <add assembly="le_nlog"/>
        </extensions>
        <targets>
          <target name="logentries" type="LogEntries" debug="true" httpPut="false" ssl="false"
          layout="${date:format=ddd MMM dd} ${time:format=HH:mm:ss} ${date:format=zzz yyyy} ${logger} : ${LEVEL}, ${message}"/>
        </targets>
        <rules>
          <logger name="*" minLevel="Debug" appendTo="logentries"/>
        </rules>
      </nlog>
      <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
          <dependentAssembly>
            <assemblyIdentity name="NLog"
                              publicKeyToken="5120e14c03d0593c"
                              culture="neutral" />
            <bindingRedirect oldVersion="2.0.0.0"
                             newVersion="2.0.1.0"/>
          </dependentAssembly>
        </assemblyBinding>
      </runtime>
    </configuration>

So, I guess, something is wrong in the bindings and/or default NuGet package install?

**Comment by omufeed** [comment]
It has been a while since this post. Had a similar error and in case sometime else has the same problem;
Converting the following config line 
<code>configuration xmlns="http://schemas.microsoft.com/.NetConfiguration/v2.0"</code>
to just
<code>configuration</code>
helped in my case.

**Comment by gearoidof** [comment]
Hi omufeed,

This library is no longer maintained by logentries, we'd recommend using our .Net library here: https://github.com/logentries/le_dotnet
